export const reviewTexts = [
  "Absolutely love this plant! It looks amazing in my living room.",
  "The plant arrived healthy and well packaged.",
  "Beautiful leaves and very easy to take care of.",
  "Exceeded my expectations, I would definitely buy again.",
  "Perfect size and great quality.",
  "Very happy with this purchase, the plant is stunning.",
  "Arrived in perfect condition and on time.",
  "Great plant for beginners, low maintenance and beautiful.",
  "The quality is excellent, looks exactly like the photos.",
  "One of the best plants I've ever bought online.",
  "Fresh, healthy and vibrant plant.",
  "The packaging was excellent and protected the plant well.",
  "Lovely plant, it instantly makes the room feel alive.",
  "Really impressed with the quality and care.",
  "Fast delivery and the plant was in great shape.",
  "Looks even better in person!",
  "Very satisfied, highly recommended.",
  "The leaves are big, green and super healthy.",
  "Amazing plant, definitely worth the price.",
  "Everything was perfect from order to delivery.",
];
